DemoData:
  data1: "Bleached Softwood Kraft Pulp Futures Historical Data.csv"

LLM:
  llm_type: azure_openai_chat
  temperature: 0

Training:
  accelerator: "gpu"
  seed: 42
  epochs: 40
  n_fold: 5
  batch_size: 64
  early_stopping: 5
  data_config:
    input_data_name: "Bleached Softwood Kraft Pulp Futures Historical Data.csv"
    target: "Price"
    drop_cols:
    features:
  model_nn:
    lr: 1e-2
    n_hidden:
      - 16
      - 32
      - 32
      - 16
    weight_decay: 1e-3
    dropout:
      - 0.1
      - 0.2
      - 0.3
  scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.5
    patience: 10
    min_lr: 1e-5

DataUpload:
  upload_dir: ./data/upload_data/
  summary_dir: ./data/summaried_data/
